### ISSUE TITLE
Validate whether the puppet-lint and other system binaries are available

### ISSUE THREAD

**Issue by mattiasgeniar** [mattiasgeniar/puppet-pre-commit-hook#9]
Right now, the pre-commit hook takes the installation of "puppet-lint" for granted. Add some validation, if the binary isn't found, explicitly show that to the user.

**Comment by mattiasgeniar** [comment]
Argh sorry Rob, I think I fixed this one in 0227f8a4f2842076e4f31dfd51559dd4cbe50030 and a1f816b21ef773a785cbb46636a0bc896125dac6 already ... I somehow missed your PR.

Could you give it an extra look? If your commits still has functionality mine doesn't I should still merge yours in.

Thanks,

Mattias

**Comment by rnelson0** [comment]
Mine doesn't have extra functionality but it uses shell builtins rather than which. See http://stackoverflow.com/a/677212/2668394

**Comment by rnelson0** [comment]
I rebased the change on top of your commits, ready for review.

**Comment by mattiasgeniar** [comment]
Thanks for the fix, I just merged it in!

**Comment by rnelson0** [comment]
You're welcome, you rock!
